[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[environments.production.variables]
NODE_ENV = "production"
PORT = "3001"
API_KEY = "your_gemini_api_key_here"
DB_HOST = "your_database_host_here"
DB_PORT = "25060"
DB_USER = "your_database_user_here"
DB_PASSWORD = "your_database_password_here"
DB_NAME = "defaultdb"
